# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa2fdd590bbf5dd520372a6c41d1652f3c76025b2e7cc38500205efdf2926ef3d39106bdcc5b8230e379a0eea353e23391709f2eb2ee1bfa1af207bf184d7aea

test:
  secret_key_base: 66e762d19f2524d6ce913837a9045c0f908a4537f53598c9fd9be24b70e44e36eedeab415faa351f5078481de47b260f1748f962b89fb244720e19740b0eba44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
